services:
  - type: web
    name: vellicate-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: GOOGLE_API_KEY
        sync: false # User must enter this in dashboard
